# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  logviewer:
    image: logviewer
    build:
      context: .
      dockerfile: LogViewer/Dockerfile
    ports:
      - '8080:80'
    environment:
      - SeriLogUrl=http://seq:5341
    depends_on:
      - seq

  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports: 
      - '8005:80'
